# Pandas series and data frames review

In [1]:
import pandas as pd
import numpy as np

In [2]:
# A numpy array
arr = np.random.randn(4) # random values from std normal distribution
print(type(arr))
print(arr, "\n")

# A pandas series made from the previous array
s = pd.Series(arr)
print(type(s))
print(s)

<class 'numpy.ndarray'>
[ 0.61564842 -0.86523515 -0.1029819  -0.5676212 ]

<class 'pandas.core.series.Series'>
0    0.615648
1   -0.865235
2   -0.102982
3   -0.567621
dtype: float64

In [ ]:
# Check In
s = pd.Series(-999, index=['A','B','C','D'])

print(s.mask(s == -999, np.nan))

A   NaN
B   NaN
C   NaN
D   NaN
dtype: float64

In [16]:
# Initialize dictionary with columns' data 
d = {'col_name_1' : pd.Series(np.arange(3)),
     'col_name_2' : pd.Series([3.1, 3.2, 3.3]),
     }

# Create data frame
df = pd.DataFrame(d)
df

   col_name_1  col_name_2
0           0         3.1
1           1         3.2
2           2         3.3

In [17]:
# Change index
df.index = ['a','b','c']
df

   col_name_1  col_name_2
a           0         3.1
b           1         3.2
c           2         3.3

In [18]:
# Check In
df.columns = ['C1', 'C2']
df.columns

Index(['C1', 'C2'], dtype='object')

### Lesson Summary
The most important thing to remember is the difference between attributes and methods. Most of your errors came from when you mixed up methods and attributes. Also, this goes hand in hand with knowing what object type you are dealing with.